language: generic
sudo: required
services:
- docker
branches:
  only:
  - development
script: docker-compose -p "dev" build
before_deploy:
- echo "login to heroku registry"
- docker login --username=_ --password="$HEROKU_TOKEN" registry.heroku.com
- docker tag dev_backend registry.heroku.com/stormy-thicket-71480/dev_backend
- docker tag dev_db registry.heroku.com/stormy-thicket-71480/dev_db
- docker tag dev_frontend registry.heroku.com/stormy-thicket-71480/dev_frontend
deploy:
  provider: heroku
  script:
  #- docker build -t registry.heroku.com/stormy-thicket-71480/web .
  - echo "push 1"
  - docker push registry.heroku.com/stormy-thicket-71480/dev_frontend
  - echo "push 2"
  - docker push registry.heroku.com/stormy-thicket-71480/dev_backend
  - echo "push 3"
  - docker push registry.heroku.com/stormy-thicket-71480/dev_db
  api_key:
    secure: HEmg42HkKwYtvy29O16ksZ085P1W/WtTM/2ZdheSKE+nVwrbwdB29rV3uFZXETM5H9+tjX0AwOay+A/g/yquA+BOFD8GOsrlusjITGfzHl1GFyGk90m9fcjo7dkSNSY8XDBEZANnRbI+o97LwGbLuwFx16wI37/F0BjPGLqIfKpK5knI0gGULazHayrd8I3mOd4XCcwDyq+5NO1sX3U1K6BxTHYY1mF3oT+AlI9/+8xiKsJn8Y11S5XSGAO5W/bsd+OCHcewpe4JK81rT4+QrxRMfoU69BTmCjY46sa1Eosag2nI+VC06PNOA1WLFsVfYH0YN5M16fuymDMWrjSeV1dYehWJIq4d+P/JQaxcWzzKsO7IyGB6qc96fACFcpmEiB0CMnK/07o1/PYXUCgPERRxgabY385amjZEBvk8FGmLbFCilu6W307MdqvnXvditHyON2MJgLHcvFow2jYqCj+Ag81yJyOs/3mmNquCghj/VfDFq7YohUhSoV2PWY4fFX9F9DhvZdzEfxjJapzEIEh9aLeVv1Td7vPMidC6yDkb+iIMZyvsE8FsTQX4STo8+wIGi2GzQDIjf37l69YYwYbtFKc5BEwNjZEFoCRSOUB/gSU9y3hOAxSZb4iNCtHZBumJbxiAkLDeSe5PuZikSt2AYtg4W2iPUQC9VJyrtdE=
  on: development
  app: stormy-thicket-71480
