language: nodejs
sudo: required
services:
- docker
branches:
  only:
  - development
script:
- docker-compose build backend
- docker-compose build frontend
deploy:
  - provider: heroku
  skip_cleanup: true
  api_key:
    secure: bLKRCa+6+rEFvpXSvKArCc5CB/dVxIpRFBcXb3mgVzYsiLT0cK+GYS6VUDmVDLCIXMsTQjOW0RjwDHW/AygtxHTcCzgFIS1fwvi2uzBMs6Sub07ZSQpM+HrLDDYEZ4rP7F7mGSFfyarNigK11ITk23/Y/on+x/3jrE656Rg5tZeGUuq127Qy6C+PskfDO5hyG5HZXV606erPr+ORofjK/XD3RmnUMPM4p1wCvH9ZWoo7LgosrTXOFl2ih9S+G2Xp1ic51q1F4sLkwg3SyWZ5cScP6sbrD8Qkt/dYFUe7wjsjdmWE4KNNsXuiX47jHZzVeY2sLBnlBy2+ECrnKmwTCRODGJPcI6pwmpnxp4y30zmj3U6y5yJ8qumJAtsMCAMxI6lwEhbsQdb535ROoUtdgiST8820lOf/uB9OkXoyxm+53S1FNRxfrNXEDSsK0RiVi66YexMBWhizwnZGLTFiFUgJopt1oCZoVMXoFRs6SrFcGokdWr/+9wLBO48Us6O3wtVqFSBceR6oP7kFaEY6Eda/gGTIiOAGatK/OnnmUtdqQ40HvjDX/+WAM4vlzGf5lluQIWVaWSfrz/q3sPXk18+HfC9hlG66tKBPbm2VRQVNjvxz9/qwwwawebDRMDXwMtCdoTCQFtrscDzbvL/orT+zaqxyarqtoGM4XVDww5E=
  on: development
  app:
  - provider: heroku
  skip_cleanup: true
  api_key:
    secure: bLKRCa+6+rEFvpXSvKArCc5CB/dVxIpRFBcXb3mgVzYsiLT0cK+GYS6VUDmVDLCIXMsTQjOW0RjwDHW/AygtxHTcCzgFIS1fwvi2uzBMs6Sub07ZSQpM+HrLDDYEZ4rP7F7mGSFfyarNigK11ITk23/Y/on+x/3jrE656Rg5tZeGUuq127Qy6C+PskfDO5hyG5HZXV606erPr+ORofjK/XD3RmnUMPM4p1wCvH9ZWoo7LgosrTXOFl2ih9S+G2Xp1ic51q1F4sLkwg3SyWZ5cScP6sbrD8Qkt/dYFUe7wjsjdmWE4KNNsXuiX47jHZzVeY2sLBnlBy2+ECrnKmwTCRODGJPcI6pwmpnxp4y30zmj3U6y5yJ8qumJAtsMCAMxI6lwEhbsQdb535ROoUtdgiST8820lOf/uB9OkXoyxm+53S1FNRxfrNXEDSsK0RiVi66YexMBWhizwnZGLTFiFUgJopt1oCZoVMXoFRs6SrFcGokdWr/+9wLBO48Us6O3wtVqFSBceR6oP7kFaEY6Eda/gGTIiOAGatK/OnnmUtdqQ40HvjDX/+WAM4vlzGf5lluQIWVaWSfrz/q3sPXk18+HfC9hlG66tKBPbm2VRQVNjvxz9/qwwwawebDRMDXwMtCdoTCQFtrscDzbvL/orT+zaqxyarqtoGM4XVDww5E=
  on: development
  app:
